import Header from "@/components/Header";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"
import { Inter } from "next/font/google";
import { SideBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GraphQL Nextjs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <main>
          <Header />
          <div className="container mx-auto grid grid-cols-3 gap-6 my-3">
            <div className="col-span-3 md:col-span-2">{children}</div>
            <div className="col-span-3 md:col-span-1">
              <SideBar />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
